version: 2

project_name: neo4j-exporter

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/neo4j-exporter
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/PapaDanielVi/neo4j-exporter/cmd/neo4j-exporter.Version={{ .Tag }}.version={{.Version}}
      - -X github.com/PapaDanielVi/neo4j-exporter/cmd/neo4j-exporter.Version={{ .Tag }}.commit={{.Commit}}
      - -X github.com/PapaDanielVi/neo4j-exporter/cmd/neo4j-exporter.Version={{ .Tag }}.buildDate={{.Date}}

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

nfpms:
  - id: neo4j-exporter
    package_name: neo4j-exporter
    maintainer: "PapaDanielVi <k2527806@gmail.com>"
    description: "Prometheus exporter for Neo4j graph databases."
    license: "MIT"
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux

homebrew_casks:
  - name: neo4j-exporter

    repository:
      owner: PapaDanielVi
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"

    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

    url:
      verified: https://github.com/PapaDanielVi/neo4j-exporter

    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/neo4j-exporter"]
          end


    homepage: "https://github.com/PapaDanielVi/neo4j-exporter"
    description: "Prometheus exporter for Neo4j graph databases."
    license: "MIT"
