version: 2

project_name: neo4j-exporter

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: cmd/neo4j-exporter/main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.buildDate={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dockers:
  - image_templates:
      - "ghcr.com/PapaDanielVi/neo4j-exporter:{{ .Tag }}-amd64"
      - "ghcr.com/PapaDanielVi/neo4j-exporter:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.com/PapaDanielVi/neo4j-exporter:{{ .Tag }}-arm64"
      - "ghcr.com/PapaDanielVi/neo4j-exporter:latest-arm64"
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.com/PapaDanielVi/neo4j-exporter:{{ .Tag }}"
    image_templates:
      - "ghcr.com/PapaDanielVi/neo4j-exporter:{{ .Tag }}-amd64"
      - "ghcr.com/PapaDanielVi/neo4j-exporter:{{ .Tag }}-arm64"
  - name_template: "ghcr.com/PapaDanielVi/neo4j-exporter:latest"
    image_templates:
      - "ghcr.com/PapaDanielVi/neo4j-exporter:latest-amd64"
      - "ghcr.com/PapaDanielVi/neo4j-exporter:latest-arm64"
