version: 2

project_name: neo4j-exporter

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/neo4j-exporter
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/PapaDanielVi/neo4j-exporter/cmd/neo4j-exporter.Version={{ .Tag }}.version={{.Version}}
      - -X github.com/PapaDanielVi/neo4j-exporter/cmd/neo4j-exporter.Version={{ .Tag }}.commit={{.Commit}}
      - -X github.com/PapaDanielVi/neo4j-exporter/cmd/neo4j-exporter.Version={{ .Tag }}.buildDate={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

brews:
  - repository:
      owner: PapaDanielVi
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"

    directory: Formula

    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

    homepage: "https://github.com/PapaDanielVi/neo4j-exporter"
    description: "Prometheus exporter for Neo4j graph databases."
    license: "MIT"

    test: |
      system "#{bin}/neo4j-exporter --version"
