{{- if .Values.custom.queries }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "neo4j-exporter.fullname" . }}-config
  labels:
    {{- include "neo4j-exporter.labels" . | nindent 4 }}
data:
  custom_queries.yaml: |
    {{- toYaml .Values.custom.queries | nindent 4 }}
{{- end }}
