---
name: Ansible Galaxy release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    name: Galaxy release
    steps:
      - uses: actions/checkout@v6

      - name: Build the collection
        run: |
          ansible-galaxy collection build ./ansible -v --force

      - name: Publish the collection on Galaxy
        run: >
          [[ "${{ secrets.ANSIBLE_GALAXY_API_KEY != '' }}" ]] || { echo
          "ANSIBLE_GALAXY_API_KEY is required to publish on galaxy" ; exit 1; }

          TARBALL=$(ls -1 ./*.tar.gz)

          ansible-galaxy collection publish "${TARBALL}" --api-key "${{ secrets.ANSIBLE_GALAXY_API_KEY }}" -v
